In [1]:
!pip install numpy

In [3]:
import numpy as np

# Difference bet array and numpy

In [5]:
# list
a = [1, 2, 3, 4]
print(a)
print(type(a))

[1, 2, 3, 4]
<class 'list'>


In [7]:
# array
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
%timeit np.arange(1,9)**4

6.55 μs ± 495 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating an array

In [19]:
# 1-D ARRAY
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))
print(arr.ndim)

[10 20 30 40 50]
<class 'numpy.ndarray'>
1


In [15]:
l = []
for i in range(1,5):
    a = int(input("enter:"))
    l.append(a)
print(np.array(l))

enter: 45
enter: 65
enter: 23
enter: 78


[45 65 23 78]


In [25]:
# 2-D ARRAY
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [11]:
arr = np.array([1,2,3,4], ndmin = 10)
print(arr)
print(type(arr))

[[[[[[[[[[1 2 3 4]]]]]]]]]]
<class 'numpy.ndarray'>


# FUNCTION

In [17]:
# zeros
arr = np.zeros(5)
arr1 = np.zeros((3,4)) # for 2D
print(arr)
print()
print(arr1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
#  Ones
arr = np.ones(5)
arr1 = np.ones((3,4)) # for 2D
print(arr)
print()
print(arr1)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# empty
arr = np.empty(5)
arr1 = np.zeros((3,4)) # for 2D
print(arr)
print()
print(arr1)

[1. 1. 1. 1. 1.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
# range 
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [27]:
# diagonal
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# linespace
arr = np.linspace(0,20,5)
arr

array([ 0.,  5., 10., 15., 20.])

In [71]:
# 2. Mathematical Functions
a = np.array([1, 4, 9])
b = np.array([4, 2, 3])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.power(a, 2))
print(np.sqrt(a))
print(np.abs(a))

[ 5  6 12]
[-3  2  6]
[ 4  8 27]
[0.25 2.   3.  ]
[ 1 16 81]
[1. 2. 3.]
[1 4 9]


In [69]:
# 3. Statistical Functions
a = np.array([10, 20, 30, 40, 50])
print(np.mean(a))
print(np.max(a))
print(np.sum(a))

30.0
50
150


In [75]:
# 4. Array Information
a = np.array([[10, 20, 30],[40, 50, 60]])

print("Array:")
print(a)

print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data type:", a.dtype)

Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int32


In [73]:
# 5. Array Manipulation
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4, 5, 6])

print("Original Array:")
print(arr)


# 1. reshape()
reshape_arr = arr.reshape(2, 3)
print("\n1. reshape():")
print(reshape_arr)


# 2. flatten()
flatten_arr = reshape_arr.flatten()
print("\n2. flatten():")
print(flatten_arr)


# 3. ravel()
ravel_arr = reshape_arr.ravel()
print("\n3. ravel():")
print(ravel_arr)


# 4. transpose()
transpose_arr = reshape_arr.T
print("\n4. transpose():")
print(transpose_arr)


# Two arrays for joining
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])


# 5. concatenate()
concat_arr = np.concatenate((a, b), axis=0)
print("\n5. concatenate():")
print(concat_arr)


# 6. vstack()
vstack_arr = np.vstack((a, b))
print("\n6. vstack():")
print(vstack_arr)


# 7. hstack()
hstack_arr = np.hstack((a, b))
print("\n7. hstack():")
print(hstack_arr)

Original Array:
[1 2 3 4 5 6]

1. reshape():
[[1 2 3]
 [4 5 6]]

2. flatten():
[1 2 3 4 5 6]

3. ravel():
[1 2 3 4 5 6]

4. transpose():
[[1 4]
 [2 5]
 [3 6]]

5. concatenate():
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

6. vstack():
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

7. hstack():
[[1 2 5 6]
 [3 4 7 8]]


# NumPy Random

In [47]:
# 1. Random number between 0 and 1
print(np.random.rand())

# 2. Multiple random numbers
print(np.random.rand(5))

# 3. Random integers
print(np.random.randint(1, 10))

# 4. For multiple numbers:
print(np.random.randint(1, 10, 5))

# 5. Random numbers from normal distribution
np.random.randn(5)

0.970323655826576
[0.75145795 0.59157384 0.17927662 0.1716868  0.56880944]
9
[5 5 4 1 3]


array([ 0.48009086, -0.07542477, -1.09011543, -0.62610708,  0.80930164])

In [55]:
# 6. Random choice --> Choose random values from an array:
arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr))

# Choose multiple:
print(np.random.choice(arr, 3))

40
[50 50 40]


In [46]:
# 7. Shuffle an array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 2 1 4 3]


In [42]:
# 8. Set a seed --> If you want the same random result every time:
np.random.seed(42)
print(np.random.randint(1, 10, 5))

[7 4 8 5 7]


# DATA TYPE

In [65]:
# Check the data type
arr = np.array([10, 20, 30])
print(arr.dtype)

# For decimal values
arr = np.array([10.5, 20.2, 30.8])
print(arr.dtype)

# Specify a data type --> You can use dtype while creating an array
arr = np.array([1, 2, 3], dtype=float)
print(arr)
print(arr.dtype)

# Convert data type --> Use .astype()
arr = np.array([1.2, 2.5, 3.8])
new_arr = arr.astype(int)
print(new_arr)

int32
float64
[1. 2. 3.]
float64
[1 2 3]


# shape vs reshape()

In [77]:
# 1. shape --> shape tells you the current structure of the array.
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a.shape)

# 2. reshape() --> reshape() changes the structure/shape of the array.
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [48]:
# 1D array
a = np.array([1, 2, 3, 4, 5, 6])
print("1D:", a)

# 1D → 2D
b = a.reshape(2, 3)
print("2D:", b)

# 2D → 1D
c = b.reshape(-1)
print("1D again:", c)

1D: [1 2 3 4 5 6]
2D: [[1 2 3]
 [4 5 6]]
1D again: [1 2 3 4 5 6]


In [79]:
# Broadcasting

In [81]:
a = np.array([10, 20, 30])
print(a + 5)

[15 25 35]


In [83]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


# Indexing AND Slicing

In [97]:
# Indexing
# 1-D
a = np.array([10, 20, 30, 40, 50])
print(a[0])   # 10
print(a[2])   # 30
print(a[-1])  # 50
# 2-D
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(a[0, 1])

10
30
50
20


In [95]:
# slicing
# 1-D
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])    # First 3 elements
print(a[2:])    # From index 2 to end
print(a[::2])   # Every 2nd element
print(a[::-1])  # Reverse array
# 2-D
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(a[0:2, 1:3])

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]
[[20 30]
 [50 60]]


# Iterating`

In [109]:
# 1. Iterating over a 1D array
a = np.array([10, 20, 30, 40, 50])
print(a)
for x in a:
    print(x)

[10 20 30 40 50]
10
20
30
40
50


In [107]:
# 2. Iterating over a 2D array
a = np.array([[10, 20, 30],
              [40, 50, 60]])

for row in a:
    print(row)

[10 20 30]
[40 50 60]


In [105]:
# 3. Iterate through every element
for row in a:
    for x in row:
        print(x)

10
20
30
40
50
60


In [111]:
# 4. Using np.nditer() --> np.nditer() is useful when you want to iterate through every element, even in multidimensional arrays.
for x in np.nditer(a):
    print(x)

10
20
30
40
50


# Copy & View

In [115]:
# copy
a = np.array([10, 20, 30, 40])

b = a.copy()
print("Original:", a)
print("Copy:", b)

Original: [10 20 30 40]
Copy: [10 20 30 40]


In [117]:
a = np.array([10, 20, 30, 40])
b = a.view()
print("Original:", a)
print("View:", b)

Original: [10 20 30 40]
View: [10 20 30 40]


# JOIN & SPILT

In [119]:
# JOIN
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))

print(c)

[1 2 3 4 5 6]


In [123]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

np.concatenate((a, b), axis=0)
# axis=0 → rows ke direction mein join 
# np.concatenate((a, b), axis=1) --> axis=1 → columns ke direction mein join

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b)))
print(np.vstack((a, b))) # row
print(np.hstack((a, b))) # column
print(np.dstack((a, b))) # height

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [135]:
# Split
a = np.array([1, 2, 3, 4, 5, 6])
b = np.split(a, 3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [137]:
a = np.array([1, 2, 3, 4, 5])
np.array_split(a, 2)

[array([1, 2, 3]), array([4, 5])]

# ARRAY Function

In [139]:
# 1. np.where() — Search --> np.where() is used to find the positions (indexes) where a condition is true.
a = np.array([10, 20, 30, 40, 50])
result = np.where(a > 30)
print(result)

(array([3, 4], dtype=int64),)


In [143]:
# 2. np.sort() — Sort --> np.sort() sorts the elements in ascending order by default.
a = np.array([40, 10, 30, 20])
print(np.sort(a))

# Descending order --> NumPy does not have a direct descending=True parameter. You can reverse the sorted array:
print(np.sort(a)[::-1])

[10 20 30 40]
[40 30 20 10]


In [145]:
# 3. np.searchsorted() — Search in a Sorted Array --> searchsorted() finds the index where a new value should be inserted while keeping the array sorted.
a = np.array([10, 20, 30, 40, 50])
print(np.searchsorted(a, 35))

# Multiple values
a = np.array([10, 20, 30, 40, 50])
print(np.searchsorted(a, [15, 35, 45]))

3
[1 3 4]


In [147]:
# 4. Filter --> Filtering means selecting only the elements that satisfy a condition.
# Boolean filtering
a = np.array([10, 20, 30, 40, 50])
result = a[a > 25]
print(result)

[30 40 50]


# Insert & delete

In [149]:
# 1. np.insert() — Insert --> np.insert() adds an element at a specific index.
# Syntax --> np.insert(array, index, value)
a = np.array([10, 20, 30, 40])
b = np.insert(a, 2, 25)
print(b)
# np.insert() returns a new array. It does not directly change the original array.

[10 20 25 30 40]


In [159]:
a = np.array([[10, 20],
              [30, 40]])
b = np.insert(a, 1, [50, 60], axis=0) 
# Here, [50, 60] is inserted at row index 1.
print(b)

[[10 20]
 [50 60]
 [30 40]]


In [163]:
a = np.array([[10, 20],
              [30, 40]])
b = np.insert(a, 1, [50, 60], axis=1)
# Here, [50, 60] is inserted at column index 1.
print(b)

[[10 50 20]
 [30 60 40]]


In [151]:
# 2. np.append() — Append --> np.append() adds elements at the end of an array.

a = np.array([10, 20, 30])
b = np.append(a, 40)
print(b)

[10 20 30 40]


In [165]:
a = np.array([[10, 20],
              [30, 40]])
b = np.append(a, [[50, 60]], axis=0)
print(b)

[[10 20]
 [30 40]
 [50 60]]


In [167]:
a = np.array([[10, 20],
              [30, 40]])
b = np.append(a, [[50],[60]], axis=1)
print(b)

[[10 20 50]
 [30 40 60]]


In [153]:
# 3. np.delete() — Delete --> np.delete() removes an element from a specific index.
# Syntax --> np.delete(array, index)
a = np.array([10, 20, 30, 40])
b = np.delete(a, 2)
print(b)

[10 20 40]


In [169]:
a = np.array([[10, 20],
              [30, 40]])
b = np.delete(a, 0, axis=0)
print(b)

[[30 40]]


In [171]:
a = np.array([[10, 20],
              [30, 40]])
b = np.delete(a, 1, axis=1)
print(b)

[[10]
 [30]]


# Matrix

In [181]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [177]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [183]:
a = np.matrix([[1,2,3],
               [4,5,6]])

b = np.matrix([[1,2],
               [3,4],
               [5,6]])

print(a * b)

[[22 28]
 [49 64]]


In [203]:
a = np.array([[1, 2, 3],[3, 4, 5]])
print(a)
print()

print(a.T)
print(np.transpose(A))
print()

print(np.swapaxes(a, 0, 1))

[[1 2 3]
 [3 4 5]]

[[1 3]
 [2 4]
 [3 5]]
[[1 3]
 [2 4]]

[[1 3]
 [2 4]
 [3 5]]


In [205]:
A = np.array([[1, 2],[3, 4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [207]:
A = np.array([[1, 2],[3, 4]])
print(np.linalg.matrix_power(A, 2))

[[ 7 10]
 [15 22]]


In [209]:
A = np.array([[1, 2],[3, 4]])
print(np.linalg.det(A))

-2.0000000000000004
